"""
Supabase Storage service.

Handles upload, download-URL generation, and deletion of files
(PDFs, DOCX, images, infographics) generated by the application.

Bucket structure:
  nd-assets/
  ├── books/{bookId}/exports/{filename}
  ├── proposals/{proposalId}/{filename}
  ├── assets/infographics/{assetId}.png
  └── assets/images/{assetId}.png
"""
from __future__ import annotations

import mimetypes
import os
from pathlib import Path
from typing import Optional

from supabase import create_client, Client

from app.config import settings

# ── Singleton Supabase client ─────────────────────────────────────────────────
_supabase: Optional[Client] = None


def get_supabase() -> Client:
    global _supabase
    if _supabase is None:
        _supabase = create_client(
            settings.supabase_url,
            settings.supabase_service_key,
        )
    return _supabase


BUCKET = settings.supabase_storage_bucket


# ── Upload helpers ────────────────────────────────────────────────────────────
def upload_bytes(
    data: bytes,
    storage_path: str,
    content_type: Optional[str] = None,
) -> str:
    """
    Upload raw bytes to Supabase Storage.
    Returns the public URL of the uploaded file.

    storage_path example: "books/abc-123/exports/whitepaper.pdf"
    """
    sb = get_supabase()

    if content_type is None:
        mime, _ = mimetypes.guess_type(storage_path)
        content_type = mime or "application/octet-stream"

    # upsert=True overwrites if the path already exists
    sb.storage.from_(BUCKET).upload(
        path=storage_path,
        file=data,
        file_options={"content-type": content_type, "upsert": "true"},
    )

    # Return the public URL
    response = sb.storage.from_(BUCKET).get_public_url(storage_path)
    return response


def upload_file(local_path: str, storage_path: str) -> str:
    """Upload a local file to Supabase Storage and return its public URL."""
    with open(local_path, "rb") as f:
        data = f.read()
    content_type, _ = mimetypes.guess_type(local_path)
    return upload_bytes(data, storage_path, content_type)


# ── Signed URL (temporary access) ────────────────────────────────────────────
def get_signed_url(storage_path: str, expires_in_seconds: int = 3600) -> str:
    """Generate a signed URL valid for `expires_in_seconds` seconds."""
    sb = get_supabase()
    response = sb.storage.from_(BUCKET).create_signed_url(
        storage_path, expires_in_seconds
    )
    return response["signedURL"]


# ── Delete ────────────────────────────────────────────────────────────────────
def delete_file(storage_path: str) -> None:
    """Remove a file from Supabase Storage."""
    sb = get_supabase()
    sb.storage.from_(BUCKET).remove([storage_path])


# ── Path builders ─────────────────────────────────────────────────────────────
def book_export_path(book_id: str, filename: str) -> str:
    return f"books/{book_id}/exports/{filename}"


def proposal_path(proposal_id: str, filename: str) -> str:
    return f"proposals/{proposal_id}/{filename}"


def asset_path(asset_id: str, extension: str) -> str:
    return f"assets/{asset_id}.{extension}"


def image_path(asset_id: str) -> str:
    return f"images/{asset_id}.png"
